source :rubygems

# Server requirements
gem 'thin' #or mongrel

# Project requirements
gem 'rake'
gem 'rack-flash'

# Component requirements
gem 'bcrypt-ruby', :require => "bcrypt"
gem 'less'
gem 'rack-less'
gem 'erubis', "~> 2.7.0"
gem 'dm-sqlite-adapter'
gem 'data_mapper'

# Test requirements
gem 'mocha', :group => "test"
gem 'rspec', :group => "test"
gem 'rack-test', :require => "rack/test", :group => "test"


# Padrino
gem 'padrino', "0.9.29"
# Padrino EDGE
# gem 'padrino', :git => "git://github.com/padrino/padrino-framework.git"
